FROM mcr.microsoft.com/devcontainers/typescript-node:22-bookworm

ENV NPM_CONFIG_PREFIX=/home/node/.npm-global
ENV PATH=$PATH:/home/node/.npm-global/bin

# Install playwright dependencies if needed
# RUN npx playwright install-deps